### ISSUE TITLE
validate Failed to determine the content type

### ISSUE THREAD

**Issue by coret** [EnnoMeijers/lodharvester#2]
Als ik de validate run (zoals beschreven in README, na crawl en map) krijg ik de volgende foutmelding:

```
$docker-compose run --rm --user 1000:1000 validate starter.sh --data centsprenten_edm.ttl --shape CHO_edm.shacl --output validate_results.ttl

Checking input parameters...

Starting SHACL validation with shapes: shapes/CHO_edm.shacl on input data data/centsprenten_edm.ttl...
org.apache.jena.riot.RiotException: Failed to determine the content type: (URI=/opt/shapes/CHO_edm.shacl : stream=null)
        at org.apache.jena.riot.RDFParser.parseURI(RDFParser.java:316)
        at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:540)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:252)ava:921)
        at org.apache.jena.riot.RDFDataMgr.loadGraph(RDFDataMgr.java:384)
        at jena.cmd.CmdMain.mainMethod(CmdMain.java:93)a:88)
        at jena.cmd.CmdMain.mainRun(CmdMain.java:45)
        at shacl.shacl.main(shacl.java:81)_validate.java:54)
```

(ook met andere, eigen data/shape bestanden)

**Comment by coret** [comment]
Workaround: rename *.shacl to *.ttl
